from ml_collections import config_dict

def get_dataset_config():
    cfg = config_dict.ConfigDict()
    cfg.dataset_path = "/scratch/phys/sin/sethih1/data_files/all_group_images_new"
    cfg.input_size = (224, 224)
    cfg.num_classes = 10
    return cfg